<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <?php
        foreach($tab as $prenom)
        {
            echo $prenom;
        }
    ?>

<!-- On utilise la deuxieme boucle  -->
    <?php foreach($tab as $age => $prenom): ?>

        <p><?php echo $prenom; ?></p>
        <!-- on utilise la 2eme méthode d'affichage -->
            <p><?= $prenom." a ".$age." ans" ?></p>
            <!-- de préférence il faut séparer les variable à afficher -->
            <p><?= $prenom ?> a <?= $age ?> ans</p>
    <?php endforeach ?>

</body>
</html>